name: List Validation

on:
  schedule:
    - cron: 0 */4 * * *
  push:
    paths-ignore:
      - reports/**
    branches:
      - master
  workflow_dispatch:

jobs:
  build-cli:
    name: List Validation
    runs-on: ubuntu-latest
    
    env:
      NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
      NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
      VECTOR_PLEXUS: ${{ secrets.VECTOR_PLEXUS }}
      LOVERS_LAB: ${{ secrets.LOVERS_LAB }}
      FTP_CREDENTIALS: ${{ secrets.FTP_CREDENTIALS }}
      DISCORD_ENDPOINTS: ${{ secrets.DISCORD_ENDPOINTS }}
    
    steps:
      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
          
      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true

      - name: Checkout Wabbajack Source
        uses: actions/checkout@v2
        with:
          repository: wabbajack-tools/wabbajack
      
      - name: Checkout Modlist Source
        uses: actions/checkout@v2
        with:
          repository: wabbajack-tools/mod-lists
          path: mod-lists
          ref: master
                    
      - name: Add System.Commandline
        continue-on-error: true
        run: dotnet nuget add source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json -n System.Commandline
      
      - name: Install dependencies
        run: dotnet restore Wabbajack.CLI/Wabbajack.CLI.csproj

      - name: Run List Validation
        run: dotnet run --project Wabbajack.CLI/Wabbajack.CLI.csproj -- validate-lists -r ${{ github.workspace }}/mod-lists/reports
        
      - name: Upload Reports
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: List Validation
          branch: master
          repository: mod-lists
          file_pattern: reports/*
        
      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        with:
          name: mod-list-reports
          path: ${{ github.workspace }}/mod-lists/reports        
    


